# This file should contain all the record creation needed to seed the database with its default gain_values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Commune.create(name: "Cerrillos",gain_value: 0.05)
Commune.create(name: "Cerro Navia",gain_value: 0.05)
Commune.create(name: "Conchalí",gain_value: 0.05)
Commune.create(name: "El Bosque",gain_value: 0.05)
Commune.create(name: "Estación Central",gain_value: 0.05)
Commune.create(name: "Huechuraba",gain_value: 0.05)
Commune.create(name: "Huechuraba",gain_value: 0.05)
Commune.create(name: "Independencia",gain_value: 0.05)
Commune.create(name: "La Cisterna",gain_value: 0.05)
Commune.create(name: "La Florida",gain_value: 0.05)
Commune.create(name: "La Granja",gain_value: 0.05)
Commune.create(name: "La Pintana",gain_value: 0.05)
Commune.create(name: "La Reina",gain_value: 0.05)
Commune.create(name: "Las Condes",gain_value: 0.05)
Commune.create(name: "Lo Barnechea",gain_value: 0.05)
Commune.create(name: "Lo Espejo",gain_value: 0.05)
Commune.create(name: "Lo Prado",gain_value: 0.05)
Commune.create(name: "Macul",gain_value: 0.05)
Commune.create(name: "Maipú",gain_value: 0.05)
Commune.create(name: "Nunoa",gain_value: 0.05)
Commune.create(name: "Pedro Aguirre Cerda",gain_value: 0.05)
Commune.create(name: "Peñalolén",gain_value: 0.05)
Commune.create(name: "Providencia",gain_value: 0.05)
Commune.create(name: "Pudahuel",gain_value: 0.05)
Commune.create(name: "Quilicura",gain_value: 0.05)
Commune.create(name: "Quinta Normal",gain_value: 0.05)
Commune.create(name: "Recoleta",gain_value: 0.05)
Commune.create(name: "Renca",gain_value: 0.05)
Commune.create(name: "Santiago",gain_value: 0.05)
Commune.create(name: "San Joaquín",gain_value: 0.05)
Commune.create(name: "San Miguel",gain_value: 0.05)
Commune.create(name: "San Ramón",gain_value: 0.05)
Commune.create(name: "Vitacura",gain_value: 0.05)
Commune.create(name: "Puente Alto",gain_value: 0.05)
Commune.create(name: "Pirque",gain_value: 0.05)
Commune.create(name: "San José de Maipo",gain_value: 0.05)
Commune.create(name: "Colina",gain_value: 0.05)
Commune.create(name: "Lampa",gain_value: 0.05)
Commune.create(name: "Tiltil",gain_value: 0.05)
Commune.create(name: "San Bernardo",gain_value: 0.05)
Commune.create(name: "Buin",gain_value: 0.05)
Commune.create(name: "Calera de Tango",gain_value: 0.05)
Commune.create(name: "Paine",gain_value: 0.05)
Commune.create(name: "Melipilla",gain_value: 0.05)
Commune.create(name: "Alhué",gain_value: 0.05)
Commune.create(name: "Curacaví",gain_value: 0.05)
Commune.create(name: "María Pinto",gain_value: 0.05)
Commune.create(name: "San Pedro",gain_value: 0.05)
Commune.create(name: "Talagante",gain_value: 0.05)
Commune.create(name: "El Monte",gain_value: 0.05)
Commune.create(name: "Isla de Maipo",gain_value: 0.05)
Commune.create(name: "Padre Hurtado",gain_value: 0.05)
Commune.create(name: "Peñaflor",gain_value: 0.05)

